[book]
authors = ["Tyler Swann"]
title = "The C++ Book"
description = "The C++ Programming Language"

language = "en"
multilingual = false

src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/oraqlle/cpp-book"

[output.html.code.hidelines]
cpp = "$"
